module Seeders
  module Brands
    class << self
      def seed
        brands.each do |name|
          Brand.find_or_create_by(name: name) do |brand|
            brand.name = name
          end
        end
      end

      def brands
        [
          "187",
          "3DM",
          "Abec11",
          "Ace",
          "Aera",
          "Airflow",
          "Alien Workshop",
          "Alva",
          "Anti-Hero",
          "Arbor",
          "Assorted",
          "Atobe",
          "Attack Trucks",
          "Baker",
          "Bear",
          "Bell",
          "Bennet",
          "Bern",
          "Black Label",
          "Blood Orange",
          "Bolts Premium",
          "BombSquad",
          "Bones",
          "Brixton",
          "Buddy Carr",
          "Bullet",
          "Bustin",
          "Buzzed",
          "Caliber",
          "Cam Caddie",
          "CandyGrind",
          "Capita",
          "Carver",
          "Cloud Ride!",
          "Comet",
          "Creature",
          "Cult",
          "Daddies Board Shop",
          "DaKine",
          "DB",
          "Deathwish",
          "DGK",
          "Diamond Supply Co.",
          "Divine",
          "Earthwing",
          "Eastside",
          "Eclectic",
          "Expedition One",
          "Fibretec",
          "Fireball",
          "Five Mile",
          "Flexdex",
          "Fullbag",
          "G-Form",
          "Girl",
          "Gold Coast",
          "GoPro",
          "Gravity",
          "Grip Gum",
          "Grizzly Grip",
          "Gullwing",
          "Gunmetal",
          "Hawgs",
          "Holesom",
          "Honey",
          "IDS",
          "Independent",
          "Jessup",
          "Jet",
          "JimZ",
          "Kahuna",
          "Kebbek",
          "Khiro",
          "Krooked",
          "Krux",
          "Kryptonics",
          "Ladera",
          "Landyachtz",
          "Leatherman",
          "Life Extention",
          "Loaded",
          "LongBoardLarry",
          "Lush",
          "Madrid",
          "Magic",
          "MBS",
          "Metro",
          "Mob",
          "Moose",
          "Motion",
          "Never Summer",
          "Ninja",
          "NoseJob",
          "OJ Wheels",
          "Omen Longboards",
          "Orangatang",
          "Original",
          "Palisades",
          "Paris Trucks",
          "Penny",
          "Poler Stuff",
          "Powell Peralta",
          "Predator",
          "Project Hardware",
          "Pro Tec",
          "Real Skateboards",
          "RAD",
          "Randal",
          "Rayne",
          "Rector",
          "Restless",
          "Revenge",
          "Riptide",
          "Riviera",
          "Roger",
          "Ronin",
          "Rush",
          "S-ONE",
          "Santa Cruz",
          "Satori Movement",
          "Sayshun",
          "Sector 9",
          "Seismic",
          "Shake Junt",
          "Shortys",
          "Silver",
          "Sims",
          "SinSystems",
          "Sk8 Mafia",
          "Skanunu",
          "SML Wheels",
          "Spitfire",
          "Stalk It",
          "Subsonic",
          "Surf Co Hawaii",
          "Surf Rodz",
          "These Wheels",
          "Thrity Two",
          "Thrasher",
          "Thunder",
          "Timeship Racing",
          "Toy Machine",
          "Tracker",
          "Triple Eight",
          "Tunnel",
          "UK Pro",
          "Ultraflate",
          "Unit",
          "Vans",
          "Venom",
          "Vew-Do",
          "Vicious",
          "Volante",
          "Wefunk",
          "Zealous",
          "Volume 4"
        ]
      end
    end
  end
end
